# Generated by Django 5.1.1 on 2024-12-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0003_alter_student_options_alter_ucitel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trieda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Trieda',
                'verbose_name_plural': 'Triedy',
                'ordering': ['nazov'],
            },
        ),
    ]
